### ISSUE TITLE
Showing prompt help command before showing the actual shell prompt 

### ISSUE THREAD

**Issue by rezmuh** [PatTheMav/minimal2#2]
Hi, I just came across this repo because i wanted to use minimal prompt with zimfw. I loaded minimal2 inside zmodule and used minimal2 as the theme. However, I got the following:

<img width="1440" alt="Screen Shot 2019-08-10 at 00 19 41" src="https://user-images.githubusercontent.com/1204244/62797027-da67a680-bb04-11e9-9229-0087d1fb4a1b.png">

**Comment by PatTheMav** [comment]
That looks more like it's being triggered by a malformed `prompt` command somewhere...

I take it you don't use the `develop` branch of `zimfw`? Also might be important to see how/where you added the module to the `zmodules` setting.

**Comment by rezmuh** [comment]
Hey @PatTheMav, I am using `master` branch on commit `b180b40`

This is what I have in `.zimrc`:

```
zmodules=(directory environment git git-info history input utility custom \
          minimal2 prompt completion syntax-highlighting history-substring-search )
zprompt_theme='minimal2'
```

**Comment by rezmuh** [comment]
Also, when I press enter, I got the following:

<img width="250" alt="Screen Shot 2019-08-10 at 15 50 34" src="https://user-images.githubusercontent.com/1204244/62819966-3a9f2c80-bb87-11e9-953c-3c47e7d25f6e.png">

**Comment by PatTheMav** [comment]
Alright, so what's happening here is that the _current_ version of the prompt theme is executed by default, as it's not dependent on `promptinit` (`zimfw` develop branch doesn't use it anymore).

So the code is automatically executed, the prompt theme is installed, and by specifying `minimal2` as the `zprompt_theme`, no built-in prompt is activated (instead the `promptinit` help is shown, as `minimal2` is no valid choice).

What you can do for now to fix this is:

1. Create a folder called `functions` inside the `minimal2` module folder
2. Delete the symlink `prompt_minimal2_setup`
3. Create a new symlink in the `functions` subfolder: `cd functions; ln -s ../minimal2.zsh-theme prompt_minimal2_setup; cd ..`
4. Restart your `zsh`

The theme should now be properly installed. I will have to think about how to support both the current master branch as well as the develop branch. Maybe just telling people to disable the `prompt` submodule might help, but the above steps should help for now.

---

As for the second issue, I have no idea what throws the `Unknown argument` errors there, but the above steps seemed to suffice in my checks.

**Comment by rezmuh** [comment]
> Alright, so what's happening here is that the _current_ version of the prompt theme is executed by default, as it's not dependent on `promptinit` (`zimfw` develop branch doesn't use it anymore).
> 
> So the code is automatically executed, the prompt theme is installed, and by specifying `minimal2` as the `zprompt_theme`, no built-in prompt is activated (instead the `promptinit` help is shown, as `minimal2` is no valid choice).
> 
> What you can do for now to fix this is:
> 
> 1. Create a folder called `functions` inside the `minimal2` module folder
> 2. Delete the symlink `prompt_minimal2_setup`
> 3. Create a new symlink in the `functions` subfolder: `cd functions; ln -s ../minimal2.zsh-theme prompt_minimal2_setup; cd ..`
> 4. Restart your `zsh`
> 

Thanks for this. You're right. Moving the symlink to `functions` did the job. Thanks for the explanation as well.

> The theme should now be properly installed. I will have to think about how to support both the current master branch as well as the develop branch. Maybe just telling people to disable the `prompt` submodule might help, but the above steps should help for now.
> 
> As for the second issue, I have no idea what throws the `Unknown argument` errors there, but the above steps seemed to suffice in my checks.

I found out the issue. It was caused by `exa`. I aliased `ls` to `exa`. So I just specified `/bin/ls` instead of `ls` in `minimal2.zsh-theme`
